apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cab-disallow-latest
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-fixed-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Do not use image tag latest. Use a commit SHA or release tag."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cab-restrict-image-registry
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: only-harbor
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Images must come from harbor.your-domain.com."
        pattern:
          spec:
            containers:
              - image: "harbor.your-domain.com/*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cab-require-resources
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-requests-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CPU and memory requests/limits are required."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cab-disallow-privileged
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-privileged-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Privileged containers are not allowed."
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(privileged): "false"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cab-require-ingress-tls
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-tls
      match:
        any:
          - resources:
              kinds:
                - Ingress
      validate:
        message: "Ingress must define TLS."
        pattern:
          spec:
            tls:
              - hosts:
                  - "?*"

