{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cab.serviceAccountName" . | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "cab.labels" . | nindent 4 }}
{{- end }}
