apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cab-staging
  namespace: argocd
spec:
  project: cab
  source:
    repoURL: git@gitlab.your-domain.com:cab/cab-booking-gitops.git
    targetRevision: main
    path: deploy/helm/cab-booking-system
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cab-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

